# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/crema',
                'doc_host': 'https://josephsmann.github.io',
                'git_url': 'https://github.com/josephsmann/crema',
                'lib_path': 'crema'},
  'syms': { 'crema.core': { 'crema.core.foo': ('core.html#foo', 'crema/core.py'),
                            'crema.core.whatisgoingon': ('core.html#whatisgoingon', 'crema/core.py')}}}