# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'whatisgoingon']

# %% ../00_core.ipynb 4
def foo():
    """ document string? """
    b = 3 + 4
    return 3

# %% ../00_core.ipynb 6
def whatisgoingon(
        a : int, # this is parameter a 
        b : int, # this isn't
        ) -> int: # and the meaning of liff
    """ this is a document string"""
    b = 3 + 4
    return b
